      
prose:
  rooturl: '_posts'
  siteurl: 'https://www.lankapura.net/blog/'
  relativeLinks: 'https://www.lankapura.net/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "JavaScript"
              value: "javascript"
            - name: ".NET"
              value: "dotnet"
            - name: "ASP.NET"
              value: "aspdotnet"
            - name: "ASP.NET"
              value: "aspdotnet"
            - name: "Angular"
              value: "angular"
    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
