backend:
  name: github
  repo: lankaapura/lankapura.net # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "source/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow
